// <auto-generated />
namespace VirtoCommerce.Platform.Data.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SettingAddCompany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SettingAddCompany));
        
        string IMigrationMetadata.Id
        {
            get { return "201606091046076_SettingAddCompany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
